<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');

    /**
    * message types in to string
    */
    $config['messageTypesInt'] = array(
                    '0'     => 'Unknown',
					'1'		=> 'WBXML Message',
                    '2'		=> 'XML Message',
                    '3'		=> 'Validation Message',
                    '4'     => 'STUN Settings',
                    '5'     => 'SIP Settings',
                    '6'     => 'VoIP Settings'

					);

    /**
    * message types strings to int
    */
    $config['messageTypesStr'] = array(
                    'Unknown'   => 0,
					'WBXML'		=> 1,
                    'XML'		=> 2,
                    'Validation'=> 3,
                    'stun'      => 4,
                    'sip'       => 5,
                    'voip'      => 6

					);

    /**
    * parser types int to string
    */
    $config['parserTypesInt'] = array(
                    '0'     => 'libwbxml',
					'1'		=> 'phpwbxml',
					);
                    

    /**
    * error messages generated by the Clickatell gateway during a validation phase
    * before they accept the message. The array lists the number => text description
    * @private
    */

    $config['validationStatusCodes'] = array (
        '001' => 'Authentication failed',
        '002' => 'Unknown username or password',
        '003' => 'Session ID expired',
        '004' => 'Account frozen',
        '005' => 'Missing session ID',
        '007' => 'IP Lockdown violation',
        '101' => 'Invalid or missing parameters',
        '102' => 'Invalid user data header',
        '103' => 'Unknown API message ID',
        '104' => 'Unknown Client Message ID',
        '105' => 'Invalid destination Address',
        '106' => 'Invalid source address',
        '107' => 'Empty message',
        '108' => 'Invalid or missing API ID',
        '109' => 'Missing message ID',
        '110' => 'Error with email message',
        '111' => 'Invalid protocol',
        '112' => 'Invalid message type',
        '113' => 'Maximum message parts exceeded',
        '114' => 'Cannot route message',
        '115' => 'Message expired',
        '116' => 'Invalid unicode data',
        '120' => 'Invalid delivery time',
        '121' => 'Destination mobile number blocked',
        '122' => 'Destination mobile opted out',
        '123' => 'Invalid Sender ID',
        '128' => 'Number delisted',
        '201' => 'Invalid batch ID',
        '202' => 'No batch template',
        '301' => 'No Credit left',
        '302' => 'Max allowed credit',
        '999' => 'Error opening connection to server'
    );

    /**
    * status messages generated by the Clickatell gateway. The array lists the number => text description
    * @private
    */

    $config['messageStatusCodes'] = array (
        ''    => 'Unknown',
        '001' => 'Message unknown',
        '002' => 'Message queued',
        '003' => 'Delivered to gateway',
        '004' => 'Received by recipient',
        '005' => 'Error with message',
        '006' => 'User cancelled message delivery',
        '007' => 'Error delivering message',
        '008' => 'OK',
        '009' => 'Routing Error',
        '010' => 'Message expired',
        '011' => 'Message Queued for later delivery',
        '012' => 'SetKia Error. Please contact an admin'
    );

    $config['send_icon'] = array(
          'src' => 'assets/images/send.png',
          'alt' => 'Send'
    );

    $config['xml_icon'] = array(
          'src' => 'assets/images/xml.png',
          'alt' => 'Send'
    );

    $config['new_voip_icon'] = array(
          'src' => 'assets/images/newvoip.png',
          'alt' => 'Send'
    );

    $config['send_voip_icon'] = array(
          'src' => 'assets/images/sendsample.png',
          'alt' => 'Send'
    );

?>
